apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: videar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: videar
        tier: backend
        track: stable
    spec:
      containers:
        - name: ui-container
          image: "mkaichen/videar:latest"
          ports:
            - name: uiport
              containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: db_host
            - name: S2T_HOST
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: s2t_host
            - name: S2T_PORT
              value: '8081'
            - name: UAS_HOST
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: uas_host
        - name: s2t-container
          image: "mkaichen/s2t:latest"
          env:
            - name: PORT
              value: '8081'
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: db_host
            - name: UAS_HOST
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: uas_host
        - name: uas-container
          image: "mkaichen/uni_audio:latest"
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: db_host
            - name: AUDIOSEARCH_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: audiosearch_app_id
            - name: AUDIOSEARCH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: videar-config
                  key: audiosearch_secret
